services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: data_QLAB
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
